# Generated by Django 4.0.1 on 2022-01-09 12:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='exercicio',
            name='nivel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercicio',
            name='titulo',
            field=models.CharField(default='e', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name=''),
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.materia')),
            ],
        ),
        migrations.AddField(
            model_name='exercicio',
            name='assunto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.assunto'),
            preserve_default=False,
        ),
    ]
