# Generated by Django 4.0.1 on 2022-01-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_materia_exercicio_nivel_exercicio_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
                'ordering': ['quiz', 'exercicio'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'ordering': ['aluno', 'data'],
            },
        ),
        migrations.AlterModelOptions(
            name='alternativa',
            options={'ordering': ['exercicio', 'texto'], 'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativa'},
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='assunto',
            options={'ordering': ['descricao'], 'verbose_name': 'Assunto', 'verbose_name_plural': 'Assunto'},
        ),
        migrations.AlterModelOptions(
            name='exercicio',
            options={'ordering': ['titulo'], 'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercício'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['descricao'], 'verbose_name': 'Matéria', 'verbose_name_plural': 'Matérias'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default='1', max_length=10, unique=True, verbose_name='Matrícula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(max_length=200, verbose_name='Texto'),
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
        migrations.AddField(
            model_name='quiz',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.aluno'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exercicio'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='resposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.alternativa'),
        ),
    ]
