# Generated by Django 4.0.1 on 2022-01-09 13:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_questionario_quiz_alter_alternativa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='correta',
            field=models.BooleanField(default=False, verbose_name='Alternativa Correta?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.assunto', verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='nivel',
            field=models.IntegerField(verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Texto'),
        ),
    ]
