# Generated by Django 4.0.1 on 2022-01-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alternativa_correta_alter_exercicio_assunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='identificacao',
            field=models.CharField(default='1', max_length=3, verbose_name='Identificação'),
            preserve_default=False,
        ),
    ]
