# Generated by Django 4.0.1 on 2022-01-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alternativa_identificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'ordering': ['exercicio', 'identificacao'], 'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativa'},
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='quiz.exercicio'),
        ),
    ]
