# Generated by Django 4.0.1 on 2022-01-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_alternativa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='resposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='quiz.alternativa', verbose_name='Resposta'),
        ),
    ]
