# Generated by Django 4.0.1 on 2022-01-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_exercicio_resposta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'ordering': ['exercicio', 'resposta'], 'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativa'},
        ),
        migrations.RemoveField(
            model_name='alternativa',
            name='identificacao',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='resposta',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='resposta',
            field=models.CharField(default='a', max_length=3, verbose_name='Resposta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercicio',
            name='respostaAluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostaAluno', to='quiz.alternativa', verbose_name='Resposta dp Aluno'),
        ),
    ]
