# Generated by Django 4.0.1 on 2022-01-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_alternativa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercicio',
            options={'ordering': ['numero'], 'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercício'},
        ),
        migrations.AddField(
            model_name='exercicio',
            name='numero',
            field=models.IntegerField(default=1, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='correta',
            field=models.BooleanField(verbose_name='Alternativa Correta'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='respostaAluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostaAluno', to='quiz.alternativa', verbose_name='Resposta do Aluno'),
        ),
    ]
