# Generated by Django 4.0.1 on 2022-01-09 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_exercicio_respostaaluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='respostaAluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostaAluno', to='quiz.alternativa', verbose_name='Resposta do Aluno'),
        ),
    ]
