# Generated by Django 4.0.1 on 2022-01-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_exercicio_respostaaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='teste',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teste'),
        ),
    ]
