# Generated by Django 4.0.1 on 2022-01-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_exercicio_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='teste',
        ),
    ]
