# Generated by Django 4.0.1 on 2022-01-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_exercicio_respostaaluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assunto',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='exercicio',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='resposta',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='assunto',
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='respostaAluno',
            field=models.CharField(max_length=3, null=True, verbose_name='Resposta'),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Assunto',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Questionario',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
